Gate some commonly unused traits behind a feature
psychon/x11rb pull request #884
Opened 2023-10-06 04:00 UTC by notgull

Adds an `extra-traits` feature that gates some of the less-commonly-used traits. It also reimplements `Debug` using a more simple implementation if it is disabled and disables request parsing.

Using this as a benchmark:

```
$ cargo clean && cargo build --no-default-features -F xfixes,randr,xkb,xinput
```

`master` is currently 19.62s to build on my laptop. This branch builds in 10.41s. That is almost halving the compile time, by my measurements. Definitely still needs improvement but at least we aren't the slowest build in `alacritty`'s tree anymore.

This is a breaking change.

2023-10-06 13:52 UTC, psychon requested changes
I think these new features should also somehow show up in `.github/workflows/CI.yml`. I'm not quite sure how. I am not even sure whether this needs to be added there or if `--all-features` is enough...

2023-10-06 13:55 UTC, psychon commented
Oh and for the test failures: I guess at least `non-amd64-test`, `windows-stable` and `non-linux-unix-test` should build with the feature enabled (= this needs to be added to `MOST_FEATURES` at the beginning of the file).

But... should `cargo test` succeed without enabling extra features? I'm a bit surprised that nothing else here failed...

2023-10-06 15:15 UTC, notgull commented on x11rb-protocol/src/protocol/bigreq.rs
>      pub fn try_parse_request(header: RequestHeader, value: &[u8]) -> Result<Self, ParseError> {
I like the idea of a different feature.

2023-10-13 14:37 UTC, psychon approved these changes

2023-10-13 14:37 UTC, psychon commented on x11rb-protocol/Cargo.toml
> +default = ["extra-traits", "std"]
Hm.... do we really want this to be enabled by default?

Well... I guess it does not matter for now. :shrug:

2023-10-13 14:40 UTC, psychon commented
@Mergifyio refresh

2023-10-13 14:41 UTC, merged